name: test conditions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:

    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.8]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: push condition
      if: startsWith(github.event_name, 'push')
      run: echo "PUSH RECOGNIZED"

    - name: pull request condition
      if: startsWith(github.event_name, 'pull_request')
      run: echo "PULL REQUEST RECOGNIZED"


