name: test docker on macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:

    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.8]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
        docker_nightly_version: snapshot-20201109

    - name: start docker compose for tests
      run: |
        docker run hello-world

