name: test docker on macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:

    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.8]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: stable
        docker_version: 20.10

    - name: run docker hello-world
      run: |
        docker run hello-world

    - name: run docker-compose
      run: |
        docker-compose up

