name: Release

on: [ push ]
  workflow_dispatch:

concurrency:
  group: release
  # Cancel-in-progress may cause incomplete releases.
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: poetry install

      - run: |
          npx --yes \
            -p semantic-release \
            -p "@semantic-release/commit-analyzer" \
            -p "@semantic-release/release-notes-generator" \
            -p "@semantic-release/changelog" \
            -p "@semantic-release/exec" \
            -p "@semantic-release/github" \
            -p "@semantic-release/git" \
            -p "@google/semantic-release-replace-plugin" \
            semantic-release --ci
        
        env:
          GITHUB_TOKEN: ${{ "{{ secrets.GITHUB_TOKEN }}" }}