name: ubuntu-sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Running django sample server inside container

        run: |
          docker-compose -f django/compose.yaml up 